var dmain=document.createElement("div");
	dmain.setAttribute("style","height:1845px");
	dmain.style.width="90%";
	dmain.style.border="1px solid grey";
	dmain.style.position="absolute";
	dmain.style.left="75px";
	dmain.style.top="25px";
	dmain.style.boxShadow="1px  1px 10px 1px grey";
	document.body.appendChild(dmain);

	var sun=document.createElement("h1");
	sun.innerHTML="The Rising Sun";
	sun.style.textAlign="center";
	sun.style.fontFamily="April Fatface";
	sun.style.fontSize="75px";
	dmain.appendChild(sun);
	var p=document.createElement("p");
	p.innerHTML="old temple with moon in background tower ";
	p.style.textAlign="center";
	p.style.position="absolute";
	p.style.top="125px";
	p.style.left="485px";
	dmain.appendChild(p);

	var div=document.createElement("div");
	div.style.width="25%";
	div.style.height="125px";
	div.style.position="absolute";
	div.style.border="1px solid lightgrey";
	div.style.top="15px";
	div.style.left="25px";
	dmain.appendChild(div);

	var img1=document.createElement("img");
	img1.setAttribute("src","https://previews.123rf.com/images/vadymvdrobot/vadymvdrobot1509/vadymvdrobot150900037/44438186-group-of-friends-hugging-together-at-the-park-in-a-circle.jpg");
	img1.style.width="25%";
	img1.style.height="75px";
	img1.style.position="absolute";
	img1.style.left="15px";
	img1.style.top="15px";
	div.appendChild(img1);
	var pwat=document.createElement("p");
	pwat.innerHTML="The Conrad Maldives Rangali Island has officially announced the opening underwater hotel.";
	pwat.style.position="absolute";
	pwat.style.left="111px";
	pwat.style.top="5px";
	div.appendChild(pwat);

	var div=document.createElement("div");
	div.style.width="25%";
	div.style.height="125px";
	div.style.position="absolute";
	div.style.border="1px solid lightgrey";
	div.style.top="15px";
	div.style.left="855px";
	dmain.appendChild(div);

	var img1=document.createElement("img");
	img1.setAttribute("src","https://previews.123rf.com/images/vadymvdrobot/vadymvdrobot1509/vadymvdrobot150900037/44438186-group-of-friends-hugging-together-at-the-park-in-a-circle.jpg");
	img1.style.width="25%";
	img1.style.height="75px";
	img1.style.position="absolute";
	img1.style.left="15px";
	img1.style.top="15px";
	div.appendChild(img1);
	var pwat=document.createElement("p");
	pwat.innerHTML="The Conrad Maldives Rangali Island has officially announced the opening underwater hotel.";
	pwat.style.position="absolute";
	pwat.style.left="111px";
	pwat.style.top="5px";
	div.appendChild(pwat);



	var hr1=document.createElement("hr");
	dmain.appendChild(hr1);

	var p1=document.createElement("p");
	p1.innerHTML="NewYork October 2 2018";
	p1.style.paddingLeft="15px";
	dmain.appendChild(p1);
	p1.style.display="inline";

	var p2=document.createElement("p");
	p2.innerHTML="wwww.aabshafdsgfhg.com";
	p2.style.display="inline";
	p2.style.paddingLeft="285px";
	dmain.appendChild(p2);

	var p3=document.createElement("p");
	p3.innerHTML="Total pages:34";
	p3.style.display="inline";
	p3.style.paddingLeft="385px";
	dmain.appendChild(p3);

	var hr2=document.createElement("hr");
	dmain.appendChild(hr2);

	var dleft=document.createElement("div");
	dleft.style.position="absolute";
	dleft.style.width="70%";
	dleft.style.height="flex";
	dleft.style.left="10px";
	dmain.appendChild(dleft);

	var d1=document.createElement("div");
	var hcar=document.createElement("h1");
	hcar.innerHTML="ELECTRIC CARS: THE FUTURE OF TRANSPORATION";
	hcar.style.fontSize="35px";
	d1.appendChild(hcar);
	var img1=document.createElement("img");
	img1.setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTHam_i414JfOJQr0LmCytunsJJDEqTIcX7Z_MT0b6o61l0Cdsb&usqp=CAU");
	d1.appendChild(img1);
	img1.style.width="95%";
	img1.style.height="195px";
	var pcar=document.createElement("p");
	pcar.innerHTML="The biggest problem facing the world’s transport planners and visionaries isn’t how to develop the most amazing new transport technologies — it’s how to fit our planet’s fast-growing population into the tight confines of its ever-growing megacities.The world’s 25 largest cities will add about 113 million people in the 15 years through 2030, according to the United Nations Population Division. About three-quarters of that growth will come in 10 emerging-world centers: Delhi, Dhaka, Kins .. "
	d1.appendChild(pcar);
	var pcar2=document.createElement("p");
	pcar2.innerHTML='Congestion isn’t confined to the ground. As cities get bigger and the incomes of the people living in them rise, the amount of air travel between the world’s cities is set to increase, too. The most intense growth will be on the shorter- and medium-haul intra-regional markets served by the likes of the Airbus SE A320 and Boeing Co. 737 — but a crucial bottleneck will be the capacity of the airports that service this traffic ';
	d1.appendChild(pcar2);
    var pcar3=document.createElement("p");
	pcar3.innerHTML='Continues at page 33';
	pcar3.style.fontFamily="Playball";
	pcar3.style.color="grey";
	d1.appendChild(pcar3);
	var hr3=document.createElement("hr");
	d1.appendChild(hr3);
	dleft.appendChild(d1);

	var c1=document.createElement("div");
	c1.style.width="50%";
	c1.style.position="absolute";
	c1.style.top="595px";
	c1.style.left="0";
	dleft.appendChild(c1);
	c1.style.height="600px";
	var c11=document.createElement("div");
	c11.style.width="100%";
	c11.style.height="250px";
	var hwat=document.createElement("h2");
	hwat.innerHTML="WORLDS FIRST UNDERWATER HOTEL VILLA";
	c11.appendChild(hwat);
	var img2=document.createElement("img");
	img2.setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTiq-JY44ECY41ZyxDZpRdykng40MZpRj5j1Lu3dBaKIX40RKvI&usqp=CAU");
	img2.style.width="31%";
	img2.style.height="115px";
	img2.style.position="absolute";
	var pwat=document.createElement("p");
	pwat.innerHTML="World's first underwater hotel opens in the Maldives. The Conrad Maldives Rangali Island has officially announced the opening of the world's first underwater hotel residence, a ground-breaking.";
	pwat.style.position="absolute";
	pwat.style.left="135px";
	pwat.style.top="75px";
	c11.appendChild(pwat);
	var pcar3=document.createElement("p");
	pcar3.innerHTML='Continues at page 33';
	pcar3.style.fontFamily="Playball";
	pcar3.style.color="grey";
	pcar3.style.position="relative";
	pcar3.style.top="135px";
	c11.appendChild(img2);
	c1.appendChild(c11);
	c11.appendChild(pcar3);
	var c12=document.createElement("div");
	c12.style.width="100%";
	c12.style.height="250px";

	var hecar=document.createElement("h2");
	hecar.innerHTML="ELECTRIC CARS:THE FUTURE OF TRANSPORATION";
	c12.appendChild(hecar);
	var img3=document.createElement("img");
	img3.setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTGTuEukcJsS8dNDLH4cVtKKHf0xbuRMRvF13sWc0NktwNPr1z4&usqp=CAU");
	img3.style.width="31%";
	img3.style.height="115px";
	img3.style.position="absolute";
	c12.appendChild(img3);
	var pecar=document.createElement("p");
	pecar.innerHTML="The world’s 25 largest cities will add about 113 million people in the 15 years through 2030, according to the United Nations Population Division. About three-quarters of that growth will come in 10 emerging-world centers: Delhi, Dhaka, Kinshasa, Shanghai, Lagos, Cairo, Chongqing, Karachi, Beijing and Mumbai.";
	pecar.style.position="absolute";
	pecar.style.left="135px";
	pecar.style.top="345px";
	c12.appendChild(pecar);
	var pcar5=document.createElement("p");
    pcar5.innerHTML='Continues at page 35';
    pcar5.style.fontFamily="Playball";
	pcar5.style.color="grey";
	pcar5.style.position="relative";
	pcar5.style.top="155px";
    c12.appendChild(pcar5);
	c1.appendChild(c12);

	var c2=document.createElement("div");
	c2.style.width="50%";
	c2.style.position="absolute";
	c2.style.top="595px";
	c2.style.right="0";
	dleft.appendChild(c2);
	c2.style.height="600px";
	var c21=document.createElement("div");
	c21.style.width="100%";
	c21.style.height="250px";
	var htal=document.createElement("h2");
	htal.innerHTML="THE TALLEST STATUE IN THE WORLD";
	c21.appendChild(htal);
	var img4=document.createElement("img");
	img4.setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSVBkDxRiTF-d8UuyTfumhHwZyiTuRYiN0YBRO1yQSSexB2_1NO&usqp=CAU");
	img4.style.width="31%";
	img4.style.height="115px";
	img4.style.position="absolute";
	var ptal=document.createElement("p");
	ptal.innerHTML="The world's tallest statue has been completed in Gujarat, India. Standing almost 600 feet tall, the Statue of Unity depicts Indian freedom fighter and politician Sardar Vallabhbhai Patel, one of the most prominent leaders of the Indian independence movement.";
	ptal.style.position="absolute";
	ptal.style.left="135px";
	ptal.style.top="75px";
	c21.appendChild(ptal);
	var pcar6=document.createElement("p");
	pcar6.innerHTML='Continues at page 33';
	pcar6.style.fontFamily="Playball";
	pcar6.style.color="grey";
	pcar6.style.position="relative";
	pcar6.style.top="135px";
	c21.appendChild(img4);
    c21.appendChild(pcar6);
    c2.appendChild(c21);

    var c22=document.createElement("div");
	c22.style.width="100%";
	c22.style.height="250px";

	var hbomb=document.createElement("h2");
	hbomb.innerHTML="SUICIDE BOMB ATTACK AT TUNIS";
	c22.appendChild(hbomb);
	var img5=document.createElement("img");
	img5.setAttribute("src","https://previews.123rf.com/images/vadymvdrobot/vadymvdrobot1509/vadymvdrobot150900037/44438186-group-of-friends-hugging-together-at-the-park-in-a-circle.jpg");
	img5.style.width="31%";
	img5.style.height="115px";
	img5.style.position="absolute";
	c22.appendChild(img5);
	var pbom=document.createElement("p");
	pbom.innerHTML="The bombings in the capital, Tunis, injured four other policemen and a civilian. The ministry blamed the attack on      terrorists.Sufyan al-Sulaiti, a spokesman for the anti-terror judicial branch, said the two attackers used a large amount of explosives and that the motorcycle they were riding was rigged with explosives";
	pbom.style.position="absolute";
	pbom.style.left="135px";
	pbom.style.top="345px";
	c22.appendChild(pbom);
	var pcar7=document.createElement("p");
    pcar7.innerHTML='Continues at page 35';
    pcar7.style.fontFamily="Playball";
	pcar7.style.color="grey";
	pcar7.style.position="relative";
	pcar7.style.top="175px";
    c22.appendChild(pcar7);
	
	c2.appendChild(c22);
	var hr4=document.createElement("hr");
	hr4.style.position="relative";
	hr4.style.top="635px";
	dleft.appendChild(hr4);

	var d2=document.createElement("div");
	d2.style.width="100%";
	d2.style.height="125px";
	d2.style.position="relative";
	d2.style.top="645px";
	dleft.appendChild(d2);
	var hbomb=document.createElement("h2");
	hbomb.innerHTML="TEN BOOKS TO CHECK OUT THIS AUTUMN";
	d2.appendChild(hbomb);
	var img5=document.createElement("img");
	img5.setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR3Jj2rwlkadOCyevRGR_WOJ-jAoSNmLd7qaS9BKfQaa0IccLO_&usqp=CAU");
	img5.style.width="15%";
	img5.style.height="85px";
	img5.style.position="absolute";
	d2.appendChild(img5);
	var pbom=document.createElement("p");
	pbom.innerHTML="Summer has made way for autumn, and the leaves of mighty oaks, towering beeches and Japanese maples are changing from shades of green to mellow yellows, flaming reds and deep browns.As October clicks in, ‘leaf peeping’ adventures — the term coined by our friends across the Pond to describe seeking out the season’s boldest colours — are increasingly popular.";
	pbom.style.position="absolute";
	pbom.style.left="155px";
	pbom.style.top="45px";
	d2.appendChild(pbom);
	var pcar7=document.createElement("p");
    pcar7.innerHTML='Continues at page 35';
    pcar7.style.fontFamily="Playball";
	pcar7.style.color="grey";
	pcar7.style.position="relative";
	pcar7.style.top="115px";
    d2.appendChild(pcar7);

	var dright=document.createElement("div");
	dright.style.position="absolute";
	dright.style.width="27%";
	dright.style.height="flex";
	dright.style.right="10px";
	dmain.appendChild(dright);

	var hmoon=document.createElement("h4");
	hmoon.innerHTML="POLITICS";
	dright.appendChild(hmoon);
	var img6=document.createElement("img");
	img6.setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSyBuqVarlEAeKC0ukL8OigrWKvRcgaGsUhE59nSH_8paiOZ9fA&usqp=CAU");
	dright.appendChild(img6);
	var hm2=document.createElement("h2");
	hm2.innerHTML="A CHINESE COMPANY TO BUILD A FAKE MOON TO REPLACE THE CITY";
	hm2.style.fontSize="28px";
	dright.appendChild(hm2);

	var pm=document.createElement("p");
	pm.innerHTML="By David and Charles cell";
	dright.appendChild(pm);
	var pm1=document.createElement("p");
	pm1.innerHTML="old temple with moon in backgroundA tower in Chengdu, China with full moon in the background. A Chinese company wants to build a moon-like structure by 2020 to rid the city of streetlights.Photo: Alamy Stock PhotoCome 2020, for children living in Chengdu, China, the book Goodnight Moon may have a completely different meaning.";
	dright.appendChild(pm1);
	var pm2=document.createElement("p");
	pm2.innerHTML="Indeed, according to an article in the People’s Daily (a widely distributed online Chinese newspaper), a local company plans to build an artificial moon that, if completed, would be eight times brighter than the actual moon. This sci-fi-like idea may come to fruition to illuminate a distance of up to 50 miles in every direction, effectively replacing all of the city streetlights.";
	dright.appendChild(pm2);
	var pcar7=document.createElement("p");
    pcar7.innerHTML='Continues at page 35';
    pcar7.style.fontFamily="Playball";
	pcar7.style.color="grey";
    dright.appendChild(pcar7);

    var d3=document.createElement("div");
    d3.style.width="100%";
    d3.style.height="719px";
    d3.style.borderStyle="double";
    dright.appendChild(d3);
    var hm=document.createElement("h2");
    hm.innerHTML="METOO MOVEMENT IN INDIA GETS BOOM";
    hm.style.position="relative";
    hm.style.left="5px";
    d3.appendChild(hm);
    var pm=document.createElement("p");
    pm.style.position="relative";
    pm.style.left="5px";
    pm.innerHTML="The Me Too movement in India is a manifestation of the international Me Too movement that began in late 2018 (and continues to the present day) in areas of Indian society including the government, the media, and the Bollywood film industry.";
    d3.appendChild(pm);
    var pcar7=document.createElement("p");
    pcar7.innerHTML='Continues at page 35';
    pcar7.style.fontFamily="Playball";
    pcar7.style.position="relative";
    pcar7.style.left="5px";
	pcar7.style.color="grey";
    d3.appendChild(pcar7);
     var hm=document.createElement("h2");
    hm.innerHTML="PLANE CRASHES IN INDONESHIA";
    hm.style.position="relative";
    hm.style.left="5px";
    d3.appendChild(hm);
    var pm=document.createElement("p");
    pm.style.position="relative";
    pm.style.left="5px";
    pm.innerHTML="The Boeing 737, owned by the low-cost airline Lion Air, went down after taking off from the capital Jakarta.Flight JT 610 was headed for the western city of Pangkal Pinang. Rescuers have recovered some bodies and personal items, including baby shoes.";
    d3.appendChild(pm);
    var pcar7=document.createElement("p");
    pcar7.innerHTML='Continues at page 35';
    pcar7.style.fontFamily="Playball";
	pcar7.style.color="grey";
	pcar7.style.position="relative";
    pcar7.style.left="5px";
    d3.appendChild(pcar7);
    var hm=document.createElement("h2");
    hm.innerHTML="CAN HUMANS SURVIVE IN MARS";
    hm.style.position="relative";
    hm.style.left="5px";
    d3.appendChild(hm);
    var pm=document.createElement("p");
    pm.style.position="relative";
    pm.style.left="5px";
    pm.innerHTML="Human survival on Mars would require living in artificial Mars habitats with complex life-support systems. One key aspect of this would be water processing systems. Being made mainly of water, a human being would die in a matter of days without it";
    d3.appendChild(pm);
    var pcar7=document.createElement("p");
    pcar7.innerHTML='Continues at page 35';
    pcar7.style.fontFamily="Playball";
	pcar7.style.color="grey";
	pcar7.style.position="relative";
    pcar7.style.left="5px";
    d3.appendChild(pcar7);

    var foot=document.createElement("div");
    dmain.appendChild(foot);
    foot.style.width="100%";
    foot.style.height="35px";
    foot.style.backgroundColor="black";
    foot.style.position="relative";
    foot.style.top="1580px";

    var p1=document.createElement("p");
	p1.innerHTML="Phone:8756765653";
	p1.style.paddingLeft="15px";
	foot.appendChild(p1);
	p1.style.display="inline";
	p1.style.color="white";

	var p2=document.createElement("p");
	p2.innerHTML="wwww.aabshafdsgfhg.com";
	p2.style.display="inline";
	p2.style.paddingLeft="285px";
	foot.appendChild(p2);
	p2.style.color="white";

	var img=document.createElement("img");
	img.setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTaYRx2we64N1lRO0ffQ8WMEJ5_xD-zNILUPKnFo_Hr9lWAz7WK&usqp=CAU");
	document.body.appendChild(img);
	img.style.width="9%";
	img.style.height="75px";
	img.style.position="relative";
	img.style.top="1935px";

	var img=document.createElement("img");
	img.setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRf82Z5l3amtdhU25i5r88PHojTdwyDz1Y-dpSUKofhAJGhQs7b&usqp=CAU");
	document.body.appendChild(img);
	img.style.width="9%";
	img.style.height="75px";
	img.style.position="relative";
	img.style.top="1935px";
