var b=document.getElementById("body");
	b.style.backgroundColor="lightyellow";
var table=document.createElement("TABLE");
table.setAttribute("width","100%");
table.setAttribute("border","1px","solid");
table.setAttribute("style","border-collapse:collapse");


var cap=document.createElement("caption");
var h4=document.createElement("h4");
h4.innerHTML="Request For New PAN Card Or/And Changes Or Connection in PAN Data";
h4.style.color="white";
var p=document.createElement("p");
p.innerHTML="Fields marked with *(asterisk) are mandatory. To avoid mistakes(s). please refer guidelines and instructions";
p.style.color="white";
cap.appendChild(h4);
cap.appendChild(p);
table.appendChild(cap);
cap.setAttribute("style","background-color:darkred");

var row=table.insertRow(0);
var cell=row.insertCell(0);
var cell1=row.insertCell(1);
cell.setAttribute("width","5%");
cell1.setAttribute("colspan","2");
var text=document.createElement("p");
var lab1=document.createElement("label");
lab1.innerHTML="yes";
lab1.style.paddingLeft="55px";
var i1=document.createElement("input");
i1.setAttribute("type","radio");
var lab2=document.createElement("label");
lab2.innerHTML="no";
var i2=document.createElement("input");
i2.setAttribute("type","radio");
text.innerHTML="Wheather cittizen of India";
cell1.appendChild(text);
text.appendChild(lab1);
text.appendChild(i1);
text.appendChild(lab2);
text.appendChild(i2);


var row1=table.insertRow(1);
var c11=row1.insertCell(0);
var c12=row1.insertCell(1);
c12.setAttribute("colspan","2");
c11.setAttribute("height","29px");
var l1=document.createElement("li");
var lab3=document.createElement("label");
lab3.innerHTML="Permanent Account Number(PAN)";
var i3=document.createElement("input");
i3.setAttribute("type","text");
l1.appendChild(lab3);
l1.appendChild(i3);
c12.appendChild(l1);

var row2=table.insertRow(2);
var c21=row2.insertCell(0);
var i=document.createElement("input");
i.setAttribute("type","checkbox");
c21.appendChild(i);
var c22=row2.insertCell(1);
c21.setAttribute("width","5%");
c21.setAttribute("height","30px");
c22.setAttribute("colspan","2");
var l2=document.createElement("li");
var lab4=document.createElement("label");
lab4.innerHTML="1.Name";
l2.appendChild(lab4);
c22.appendChild(l2);

var row3=table.insertRow(3);
var c31=row3.insertCell(0);
var c32=row3.insertCell(1);
c32.setAttribute("colspan","2");
var t1=document.createElement("p");
var lab5=document.createElement("label");
lab5.innerHTML="Shri/Mr";
lab5.style.paddingLeft="55px";
var i4=document.createElement("input");
i4.setAttribute("type","radio");
var lab6=document.createElement("label");
lab6.innerHTML="Sm.Mrs.";
var i5=document.createElement("input");
i5.setAttribute("type","radio");
var lab7=document.createElement("label");
lab7.innerHTML="Kumari";
var i6=document.createElement("input");
i6.setAttribute("type","radio");
t1.innerHTML="Title";
c32.appendChild(t1);
t1.appendChild(lab5);
t1.appendChild(i4);
t1.appendChild(lab6);
t1.appendChild(i5);
t1.appendChild(lab7);
t1.appendChild(i6);

var row4=table.insertRow(4);
var c41=row4.insertCell(0);
var c42=row4.insertCell(1);
c42.setAttribute("colspan","2");
c41.setAttribute("height","30px");
var pl=document.createElement("p");
var lab8=document.createElement("label");
lab8.innerHTML="Last Name/Surname";
var i7=document.createElement("input");
i7.setAttribute("type","text");
var lab9=document.createElement("label");
lab9.innerHTML="First Name";
var i8=document.createElement("input");
i8.setAttribute("type","text");
var lab10=document.createElement("label");
lab10.innerHTML="Middle Name";
var i9=document.createElement("input");
i9.setAttribute("type","text")
pl.appendChild(lab8);
pl.appendChild(i7);
pl.appendChild(lab9);
pl.appendChild(i8);
pl.appendChild(lab10);
pl.appendChild(i9);
c42.appendChild(pl);

var row5=table.insertRow(5);
var c51=row5.insertCell(0);
var c52=row5.insertCell(1);
c52.setAttribute("colspan","2");
c51.setAttribute("height","30px");
var ps=document.createElement("li");
ps.innerHTML="Name as you wouldlike it printed on the card";
var sp1=document.createElement("span");
sp1.style.color="blue";
sp1.innerHTML="(Prefix like Shri,Smt,Kumari,Late,Dr,CA,Ms,Mrs,M/s,Alias etc. are not allowed.)";
ps.appendChild(sp1);
c52.appendChild(ps);

var row6=table.insertRow(6);
var c61=row6.insertCell(0);
var c62=row6.insertCell(1);
c62.setAttribute("colspan","2");
c61.setAttribute("height","30px");
var i10=document.createElement("input");
i10.setAttribute("type","text");
i10.setAttribute("type","text");
i10.style.width="45%";
c62.appendChild(i10);

var row7=table.insertRow(7);
var c71=row7.insertCell(0);
var c72=row7.insertCell(1);
c72.setAttribute("colspan","2");
c71.setAttribute("height","30px");
var ps=document.createElement("p");
ps.innerHTML="Details of parents";
var sp1=document.createElement("span");
sp1.style.color="blue";
sp1.innerHTML="(Prefix like Shri,Smt,Kumari,Late,Dr,CA,Ms,Mrs,M/s,Alias etc. are not allowed.)";
ps.appendChild(sp1);
c72.appendChild(ps);

var row8=table.insertRow(8);
var c81=row8.insertCell(0);
var c82=row8.insertCell(1);
var c83=row8.insertCell(2);
c83.style.width="55%";
c81.setAttribute("height","30px");
var ps=document.createElement("p");
ps.innerHTML="Whether mother is single parent and you wish to apply for PAN by furnishing the name of your";
var lab11=document.createElement("label");
lab11.innerHTML="yes";
var i11=document.createElement("input");
i11.setAttribute("type","radio");
var lab12=document.createElement("label");
lab12.innerHTML="no";
var i12=document.createElement("input");
i12.setAttribute("type","radio");
c82.appendChild(ps);
c83.appendChild(lab11);
c83.appendChild(i11);
c83.appendChild(lab12);
c83.appendChild(i12)

var row9=table.insertRow(9);
var c91=row9.insertCell(0);
var c92=row9.insertCell(1);
c92.setAttribute("colspan","2");
c91.setAttribute("height","30px");
var i=document.createElement("input");
i.setAttribute("type","checkbox");
c91.appendChild(i);
var ps1=document.createElement("li");
ps1.innerHTML="Father's Name";
var sp2=document.createElement("span");
sp2.style.color="blue";
sp2.innerHTML="(Mandatory field. Even married women should give faher's name only.)";
ps1.appendChild(sp2);
c92.appendChild(ps1);

var row10=table.insertRow(10);
var c101=row10.insertCell(0);
var c102=row10.insertCell(1);
c102.setAttribute("colspan","2");
c101.setAttribute("height","30px");
var pl1=document.createElement("p");
var lab13=document.createElement("label");
lab13.innerHTML="Last Name/Surname";
var i13=document.createElement("input");
i13.setAttribute("type","text");
var lab14=document.createElement("label");
lab14.innerHTML="First Name";
var i14=document.createElement("input");
i14.setAttribute("type","text");
var lab15=document.createElement("label");
lab15.innerHTML="Middle Name";
var i15=document.createElement("input");
i15.setAttribute("type","text")
pl1.appendChild(lab13);
pl1.appendChild(i13);
pl1.appendChild(lab14);
pl1.appendChild(i14);
pl1.appendChild(lab15);
pl1.appendChild(i15);
c102.appendChild(pl1);

var row11=table.insertRow(11);
var c111=row11.insertCell(0);
var c112=row11.insertCell(1);
c112.setAttribute("colspan","2");
c111.setAttribute("height","30px");
var i=document.createElement("input");
i.setAttribute("type","checkbox");
c111.appendChild(i);
var ps2=document.createElement("li");
ps2.innerHTML="Mother's Name";
var sp3=document.createElement("span");
sp3.style.color="blue";
sp3.innerHTML="(This field is optional.)";
ps2.appendChild(sp3);
c112.appendChild(ps2);

var row12=table.insertRow(12);
var c121=row12.insertCell(0);
var c122=row12.insertCell(1);
c122.setAttribute("colspan","2");
c121.setAttribute("height","30px");
var pl2=document.createElement("p");
var lab16=document.createElement("label");
lab16.innerHTML="Last Name/Surname";
var i16=document.createElement("input");
i16.setAttribute("type","text");
var lab17=document.createElement("label");
lab17.innerHTML="First Name";
var i17=document.createElement("input");
i17.setAttribute("type","text");
var lab18=document.createElement("label");
lab18.innerHTML="Middle Name";
var i18=document.createElement("input");
i18.setAttribute("type","text")
pl2.appendChild(lab16);
pl2.appendChild(i16);
pl2.appendChild(lab17);
pl2.appendChild(i17);
pl2.appendChild(lab18);
pl2.appendChild(i18);
c122.appendChild(pl2);

var row13=table.insertRow(13);
var c131=row13.insertCell(0);
var c132=row13.insertCell(1);
var c133=row13.insertCell(2);
c133.style.width="45%";
c131.setAttribute("height","30px");
var ps3=document.createElement("p");
ps3.innerHTML="Select parent which is to be printed on the card In case no option is provided then PAN car will be issued with faher's name";
var lab11=document.createElement("label");
lab11.innerHTML="Father Name";
var i11=document.createElement("input");
i11.setAttribute("type","radio");
var lab12=document.createElement("label");
lab12.innerHTML="Mother Name";
var i12=document.createElement("input");
i12.setAttribute("type","radio");
c132.appendChild(ps3);
c133.appendChild(lab11);
c133.appendChild(i11);
c133.appendChild(lab12);
c133.appendChild(i12);

var row14=table.insertRow(14);
var c141=row14.insertCell(0);
var c142=row14.insertCell(1);
var c143=row14.insertCell(2);
c143.style.width="45%";
c141.setAttribute("height","30px");
var i=document.createElement("input");
i.setAttribute("type","checkbox");
c141.appendChild(i);
var ps3=document.createElement("li");
ps3.innerHTML="5.Date of Birth/Incorporation /Agreement/Parnership or Trust Deed/Formation of Body of Individuals/Association of persons";
var lab11=document.createElement("label");
lab11.innerHTML="DOB";
var i11=document.createElement("input");
i11.setAttribute("type","date");
c142.appendChild(ps3);
c143.appendChild(lab11);
c143.appendChild(i11);

var row15=table.insertRow(15);
var c151=row15.insertCell(0);
var c152=row15.insertCell(1);
var c153=row15.insertCell(2);
c153.style.width="45%";
c151.setAttribute("height","30px");
var i=document.createElement("input");
i.setAttribute("type","checkbox");
c151.appendChild(i);
var ps3=document.createElement("li");
ps3.innerHTML="6.Gender";
var lab11=document.createElement("label");
lab11.innerHTML="Male";
var i11=document.createElement("input");
i11.setAttribute("type","radio");
var lab12=document.createElement("label");
lab12.innerHTML="Female";
var i12=document.createElement("input");
i12.setAttribute("type","radio");
var lab13=document.createElement("label");
lab13.innerHTML="Transgender";
var i13=document.createElement("input");
i13.setAttribute("type","radio");
c152.appendChild(ps3);
c153.appendChild(lab11);
c153.appendChild(i11);
c153.appendChild(lab12);
c153.appendChild(i12);
c153.appendChild(lab13);
c153.appendChild(i13);

var row16=table.insertRow(16);
var c161=row16.insertCell(0);
var c162=row16.insertCell(1);
c161.setAttribute("height","30px");
var i=document.createElement("input");
i.setAttribute("type","checkbox");
c161.appendChild(i);
c162.setAttribute("colspan","2");
var ps3=document.createElement("li");
ps3.innerHTML="7.PhotoMismatch";
c162.appendChild(ps3);

var row17=table.insertRow(17);
var c171=row17.insertCell(0);
var c172=row17.insertCell(1);
c171.setAttribute("height","30px");
var i=document.createElement("input");
i.setAttribute("type","checkbox");
c171.appendChild(i);
c172.setAttribute("colspan","2");
var ps3=document.createElement("li");
ps3.innerHTML="8.SignatureMismatch";
c172.appendChild(ps3);

var row18=table.insertRow(18);
var c181=row18.insertCell(0);
var c182=row18.insertCell(1);
var c183=row18.insertCell(2);
c183.style.width="45%";
c181.setAttribute("height","30px");
var i=document.createElement("input");
i.setAttribute("type","checkbox");
c181.appendChild(i);
var ps3=document.createElement("li");
ps3.innerHTML="9.Address For Communication";
var lab11=document.createElement("label");
lab11.innerHTML="Residential";
var i11=document.createElement("input");
i11.setAttribute("type","radio");
var lab12=document.createElement("label");
lab12.innerHTML="Office";
var i12=document.createElement("input");
i12.setAttribute("type","radio");
c182.appendChild(ps3);
c183.appendChild(lab11);
c183.appendChild(i11);
c183.appendChild(lab12);
c183.appendChild(i12);

var row19=table.insertRow(19);
var c191=row19.insertCell(0);
var c192=row19.insertCell(1);
var c193=row19.insertCell(2);
c191.setAttribute("height","30px");
var ps3=document.createElement("li");
ps3.innerHTML="Office Name(to be filled only in case of office address)";
var i11=document.createElement("input");
i11.setAttribute("type","text");
i11.style.width="65%";
i11.style.height="29px";
c192.appendChild(ps3);
c193.appendChild(i11);

var row20=table.insertRow(20);
var c201=row20.insertCell(0);
var c202=row20.insertCell(1);
var c203=row20.insertCell(2);
c201.setAttribute("height","30px");
var ps3=document.createElement("li");
ps3.innerHTML="Flat/Door/Black No";
var i11=document.createElement("input");
i11.setAttribute("type","text");
i11.style.width="55%";
i11.style.height="29px";
c202.appendChild(ps3);
c203.appendChild(i11);

var row21=table.insertRow(21);
var c211=row21.insertCell(0);
var c212=row21.insertCell(1);
var c213=row21.insertCell(2);
var ps3=document.createElement("li");
ps3.innerHTML="Name of Premises/Building/Village";
var i11=document.createElement("input");
i11.setAttribute("type","text");
i11.style.width="55%";
i11.style.height="29px";
c212.appendChild(ps3);
c213.appendChild(i11);

var row22=table.insertRow(22);
var c221=row22.insertCell(0);
var c222=row22.insertCell(1);
var c223=row22.insertCell(2);
var ps3=document.createElement("li");
ps3.innerHTML="Road/Street/Lane/Post Office";
var i11=document.createElement("input");
i11.setAttribute("type","text");
i11.style.width="55%";
i11.style.height="29px";
c222.appendChild(ps3);
c223.appendChild(i11);

var row23=table.insertRow(23);
var c231=row23.insertCell(0);
var c232=row23.insertCell(1);
var c233=row23.insertCell(2);
var ps3=document.createElement("li");
ps3.innerHTML="Area/Locality/Taluka/Sub-Division";
var i11=document.createElement("input");
i11.setAttribute("type","text");
i11.style.width="55%";
i11.style.height="29px";
c232.appendChild(ps3);
c233.appendChild(i11);

var row24=table.insertRow(24);
var c241=row24.insertCell(0);
var c242=row24.insertCell(1);
var c243=row24.insertCell(2);
var ps3=document.createElement("li");
ps3.innerHTML="Town/city/District";
var i11=document.createElement("input");
i11.setAttribute("type","text");
i11.style.width="55%";
i11.style.height="29px";
c242.appendChild(ps3);
c243.appendChild(i11);

var row25=table.insertRow(25);
var c251=row25.insertCell(0);
var c252=row25.insertCell(1);
var c253=row25.insertCell(2);
var ps3=document.createElement("li");
ps3.innerHTML="State/Union Territory";
var i11=document.createElement("Select");
var op=document.createElement("option");
op.innerHTML="--Please Select--";
op.setAttribute("selected","selected");
i11.style.width="59%";
i11.style.height="29px";
i11.style.backgroundColor="lightgrey";
c252.appendChild(ps3);
i11.appendChild(op);
c253.appendChild(i11);

var row26=table.insertRow(26);
var c261=row26.insertCell(0);
var c262=row26.insertCell(1);
var c263=row26.insertCell(2);
var ps3=document.createElement("li");
ps3.innerHTML="PIN(Inicating PIN is mandatory)";
var i11=document.createElement("input");
i11.setAttribute("type","text");
i11.style.width="25%";
i11.style.height="29px";
c262.appendChild(ps3);
c263.appendChild(i11);

var row27=table.insertRow(27);
var c271=row27.insertCell(0);
var c272=row27.insertCell(1);
var c273=row27.insertCell(2);
var ps3=document.createElement("li");
ps3.innerHTML="Country";
var i11=document.createElement("Select");
var op=document.createElement("option");
op.innerHTML="--Please Select--";
op.setAttribute("selected","selected");
i11.style.width="75%";
i11.style.height="29px";
i11.style.backgroundColor="lightgrey";
c272.appendChild(ps3);
i11.appendChild(op);
c273.appendChild(i11);

var row28=table.insertRow(28);
var c281=row28.insertCell(0);
var c282=row28.insertCell(1);
var c283=row28.insertCell(2);
var ps3=document.createElement("li");
ps3.innerHTML="ZIP";
var i11=document.createElement("input");
i11.setAttribute("type","text");
i11.style.width="25%";
i11.style.height="29px";
c282.appendChild(ps3);
c283.appendChild(i11);

var row29=table.insertRow(29);
var c291=row29.insertCell(0);
var c292=row29.insertCell(1);
c291.setAttribute("height","30px");
var i=document.createElement("input");
i.setAttribute("type","checkbox");
c291.appendChild(i);
c292.setAttribute("colspan","2");
var ps3=document.createElement("p");
ps3.innerHTML="10.If you desire to update your other adress ,give required detail & Submit proof of other address also";
c292.appendChild(ps3);

var row30=table.insertRow(30);
var c301=row30.insertCell(0);
var c302=row30.insertCell(1);
c301.setAttribute("height","30px");
c302.setAttribute("colspan","2");
var ps3=document.createElement("li");
ps3.innerHTML=" 11.TelePhone No (Country code is compulsory) ";
var div1=document.createElement("div");
var div2=document.createElement("div");
 var div3=document.createElement("div");
 div2.style.float="left";
 div2.appendChild(ps3);
 div3.style.float="right";
 div3.style.width="53%";
 div3.setAttribute("border","1px","solid");
 var l1=document.createElement("lable");
l1.innerHTML="Country code(ISD code) ";
var i11=document.createElement("Select");
var op=document.createElement("option");
op.innerHTML="--Please Select--";
op.setAttribute("selected","selected");
i11.style.width="75%";
i11.style.height="29px";
i11.style.backgroundColor="lightgrey";
i11.appendChild(op);

var tab=document.createElement("TABLE");
tab.style.width="100%";

var r=tab.insertRow(0);
var c1=r.insertCell(0);
var c2=r.insertCell(1);
var i1=document.createElement("input");
i1.setAttribute("type","radio");
var l11=document.createElement("label");
l11.innerHTML="Mobile no";
c1.appendChild(i1);
c1.appendChild(l11);
var i2=document.createElement("input");
i2.setAttribute("type","radio");
var l2=document.createElement("label");
l2.innerHTML="Telephone no";
c2.appendChild(i2);
c2.appendChild(l2);
var r1=tab.insertRow(1);
var c11=r1.insertCell(0);
var c12=r1.insertCell(1);
var i12=document.createElement("input");
i12.setAttribute("type","text");
var lab=document.createElement("label");
lab.innerHTML="Area/STD code";
c11.appendChild(lab);
c11.appendChild(i12);
var i22=document.createElement("input");
i22.setAttribute("type","text");
var lab2=document.createElement("label");
lab2.innerHTML="Area/STD code";
c12.appendChild(lab2);
c12.appendChild(i22);

div3.appendChild(l1);
div3.appendChild(i11);
div3.appendChild(tab);
div1.appendChild(div2);
div1.appendChild(div3);
c302.appendChild(div1);
var div3=document.createElement("div");

var row31=table.insertRow(31);
var c311=row31.insertCell(0);
var c312=row31.insertCell(1);
var c313=row31.insertCell(2);
var ps3=document.createElement("li");
ps3.innerHTML="Email ID";
var i11=document.createElement("input");
i11.setAttribute("type","text");
i11.style.width="55%";
i11.style.height="29px";
c312.appendChild(ps3);
c313.appendChild(i11);

var row32=table.insertRow(32);
var c321=row32.insertCell(0);
var c322=row32.insertCell(1);
var c323=row32.insertCell(2);
var ps3=document.createElement("li");
ps3.innerHTML="In case of citizen of India,then";
var i1=document.createElement("input");
i1.setAttribute("type","radio");
var l11=document.createElement("label");
l11.innerHTML="AADHAAR";
c323.appendChild(i1);
c323.appendChild(l11);
var i2=document.createElement("input");
i2.setAttribute("type","radio");
var l2=document.createElement("label");
l2.innerHTML="EID";
c323.appendChild(i2);
c323.appendChild(l2);
c322.appendChild(ps3);

var row33=table.insertRow(33);
var c331=row33.insertCell(0);
var i=document.createElement("input");
i.setAttribute("type","checkbox");
c331.appendChild(i);
var c332=row33.insertCell(1);
var c333=row33.insertCell(2);
var ps3=document.createElement("li");
ps3.innerHTML="12.AADHAAR number:";
var i11=document.createElement("input");
i11.setAttribute("type","text");
i11.style.width="25%";
i11.style.height="29px";
var l11=document.createElement("label");
l11.innerHTML="In case AADHAAR number is provided,then proof of AADHAAR along with supporting documents is to be submitted to NSDL";
c332.appendChild(ps3);
c333.appendChild(i11);
c333.appendChild(l11);

var row34=table.insertRow(34);
var c341=row34.insertCell(0);
var c342=row34.insertCell(1);
var c343=row34.insertCell(2);
var ps3=document.createElement("li");
ps3.innerHTML="Name as per AADHAAR letter or as per the enrollment ID of Aadhar application form";
var i11=document.createElement("input");
i11.setAttribute("type","text");
i11.style.width="95%";
i11.style.height="29px";
c342.appendChild(ps3);
c343.appendChild(i11);

var row35=table.insertRow(35);
var c351=row35.insertCell(0);
var c352=row35.insertCell(1);
var c353=row35.insertCell(2);
var ps3=document.createElement("li");
ps3.innerHTML="13.GSTN";
var i11=document.createElement("input");
i11.setAttribute("type","text");
i11.style.width="35%";
i11.style.height="29px";
c352.appendChild(ps3);
c353.appendChild(i11);

var row36=table.insertRow(36);
var c361=row36.insertCell(0);
var c362=row36.insertCell(1);
c362.setAttribute("colspan","2");
var i=document.createElement("input");
i.setAttribute("type","checkbox");
c361.appendChild(i);
var ps3=document.createElement("li");
ps3.innerHTML="14. Mention other Permanent Account Number(PANs)if any ,indavernantly alotted to you  & Submit proof of surrendered PAN(s) along with the application.";
c362.appendChild(ps3);

var row37=table.insertRow(37);
var c371=row37.insertCell(0);
var c372=row37.insertCell(1);
var c373=row37.insertCell(2);
var lab1=document.createElement("label");
lab1.innerHTML="PAN1";
var i1=document.createElement("input");
i1.setAttribute("type","text");
var lab2=document.createElement("label");
lab2.innerHTML="PAN2";
var i2=document.createElement("input");
i2.setAttribute("type","text");
c372.appendChild(lab1);
c372.appendChild(i1);
c373.appendChild(lab2);
c373.appendChild(i2);


var row38=table.insertRow(38);
var c381=row38.insertCell(0);
var c382=row38.insertCell(1);
var c383=row38.insertCell(2);
var lab1=document.createElement("label");
lab1.innerHTML="PAN1";
var i1=document.createElement("input");
i1.setAttribute("type","text");
var lab2=document.createElement("label");
lab2.innerHTML="PAN2";
var i2=document.createElement("input");
i2.setAttribute("type","text");
c382.appendChild(lab1);
c382.appendChild(i1);
c383.appendChild(lab2);
c383.appendChild(i2);

var row39=table.insertRow(39);
var c391=row39.insertCell(0);
var c392=row39.insertCell(1);
c392.setAttribute("colspan","2");

var p=document.createElement("p");
var lab1=document.createElement("label");
lab1.innerHTML="I/we";
var i1=document.createElement("input");
i1.setAttribute("type","text");
i1.style.width="55%";
var lab2=document.createElement("label");
lab2.innerHTML=", the applicant,in the capacity of";
var i11=document.createElement("Select");
var op=document.createElement("option");
op.innerHTML="--Please Select--";
op.setAttribute("selected","selected");
i11.style.width="29%";
i11.style.height="29px";
i11.style.backgroundColor="lightgrey";
i11.appendChild(op);
var lab3=document.createElement("label");
lab3.innerHTML="do hereby declare that what is stated above is true to the best of my information and belief.";
var i3=document.createElement("input");
i3.setAttribute("type","text");
i3.style.width="15%";
var lab4=document.createElement("label");
lab4.innerHTML="I have enclosed";
var i4=document.createElement("input");
i4.setAttribute("type","text");
i4.style.width="55%";
var lab5=document.createElement("label");
lab5.innerHTML="(number of documents) in support of proposed changes/Corrections";
p.appendChild(lab1);
p.appendChild(i1);
p.appendChild(lab2);
p.appendChild(i11);
p.appendChild(lab3);
p.appendChild(lab4);
p.appendChild(i3);
p.appendChild(i4);
p.appendChild(lab5);
c392.appendChild(p);

var row40=table.insertRow(40);
var c401=row40.insertCell(0);
var c402=row40.insertCell(1);
c402.setAttribute("colspan","2");
var lab1=document.createElement("label");
lab1.innerHTML="Place";
var i1=document.createElement("input");
i1.setAttribute("type","text");
c402.appendChild(lab1);
c402.appendChild(i1);

var row41=table.insertRow(41);
var c411=row41.insertCell(0);
var c412=row41.insertCell(1);
c412.setAttribute("colspan","2")
var p=document.createElement("p");
var lab1=document.createElement("label");
lab1.innerHTML="I have enclosed ";
var i1=document.createElement("Select");
var op1=document.createElement("option");
op1.innerHTML="--Please Select--";
op1.setAttribute("selected","selected");
i1.style.width="85%";
i1.style.height="29px";
i1.style.backgroundColor="lightgrey";
i1.appendChild(op1);
var lab2=document.createElement("label");
lab2.innerHTML="as proof of identity,";
var i11=document.createElement("Select");
var op=document.createElement("option");
op.innerHTML="--Please Select--";
op.setAttribute("selected","selected");
i11.style.width="65%";
i11.style.height="29px";
i11.style.backgroundColor="lightgrey";
i11.appendChild(op);
var lab3=document.createElement("label");
lab3.innerHTML="as proof of address and ";
var i3=document.createElement("Select");
var op2=document.createElement("option");
op2.innerHTML="--Please Select--";
op2.setAttribute("selected","selected");
i3.style.width="75%";
i3.style.height="29px";
i3.style.backgroundColor="lightgrey";
i3.appendChild(op2);
var lab4=document.createElement("label");
lab4.innerHTML="as proof of PAN allotted";
var i4=document.createElement("Select");
var op3=document.createElement("option");
op3.innerHTML="--Please Select--";
op3.setAttribute("selected","selected");
i4.style.width="75%";
i4.style.height="29px";
i4.style.backgroundColor="lightgrey";
i4.appendChild(op3);
var lab5=document.createElement("label");
lab5.innerHTML="as proof of date of birth and";
p.appendChild(lab1);
p.appendChild(i1);
p.appendChild(lab2);
p.appendChild(i2);
p.appendChild(lab3);
p.appendChild(i3);
p.appendChild(lab4);
p.appendChild(i4);
p.appendChild(lab5);
c412.appendChild(p);

var row42=table.insertRow(42);
var c421=row42.insertCell(0);
var c422=row42.insertCell(1);
c422.setAttribute("colspan","2");
var text=document.createElement("p");
var lab1=document.createElement("label");
lab1.innerHTML="Physical  PAN Card & e-PAN Card";
lab1.style.paddingLeft="55px";
var i1=document.createElement("input");
i1.setAttribute("type","radio");
var lab2=document.createElement("label");
lab2.innerHTML="Only e-PAN Card";
var i2=document.createElement("input");
i2.setAttribute("type","radio");
text.innerHTML="whether you wish to have?";
c422.appendChild(text);
text.appendChild(lab1);
text.appendChild(i1);
text.appendChild(lab2);
text.appendChild(i2);

var row43=table.insertRow(43);
var c431=row43.insertCell(0);
var c432=row43.insertCell(1);
c432.setAttribute("colspan","2");
var ps3=document.createElement("p");
ps3.innerHTML="Other Details";
c432.appendChild(ps3);

var row44=table.insertRow(44);
var c441=row44.insertCell(0);
var c442=row44.insertCell(1);
c442.setAttribute("colspan","2");
var ps3=document.createElement("p");
ps3.innerHTML="1.Depository Account Details";
c442.appendChild(ps3);

var row45=table.insertRow(45);
var c451=row45.insertCell(0);
var c452=row45.insertCell(1);
var c453=row45.insertCell(2);
var lab1=document.createElement("label");
lab1.innerHTML="DP ID:";
var i1=document.createElement("input");
i1.setAttribute("type","text");
var lab2=document.createElement("label");
lab2.innerHTML="Client ID";
var i2=document.createElement("input");
i2.setAttribute("type","text");
c452.appendChild(lab1);
c452.appendChild(i1);
c453.appendChild(lab2);
c453.appendChild(i2);

var row46=table.insertRow(46);
var c461=row46.insertCell(0);
var c462=row46.insertCell(1);
c462.setAttribute("colspan","2");
var ps3=document.createElement("p");
ps3.innerHTML="2.Payment Details";
c462.appendChild(ps3);
var row47=table.insertRow(47);
var c471=row47.insertCell(0);
var c472=row47.insertCell(1);
var i=document.createElement("input");
i.setAttribute("type","checkbox");
c471.appendChild(i);
c472.setAttribute("colspan","2");
var ps3=document.createElement("p");
ps3.innerHTML="Onine Payment";
c472.appendChild(ps3);

document.body.appendChild(table);
var text=document.createElement("h3");
var lab1=document.createElement("label");
lab1.innerHTML="yes";
lab1.style.paddingLeft="55px";
var i1=document.createElement("input");
i1.setAttribute("type","radio");
var lab2=document.createElement("label");
lab2.innerHTML="no";
var i2=document.createElement("input");
i2.setAttribute("type","radio");
text.innerHTML="For Paperless PAN Application:";
cell1.appendChild(text);
text.appendChild(lab1);
text.appendChild(i1);
text.appendChild(lab2);
text.appendChild(i2);
document.body.appendChild(text);
var d1=document.createElement("p");
var i1=document.createElement("input");
i1.setAttribute("type","radio");
var lab2=document.createElement("label");
lab2.innerHTML="DSC";
var i3=document.createElement("Select");
var op2=document.createElement("option");
op2.innerHTML="--Please Select--";
op2.setAttribute("selected","selected");
i3.style.width="35%";
i3.style.height="29px";
i3.style.backgroundColor="lightgrey";
i3.appendChild(op2);
d1.appendChild(i1);
d1.appendChild(lab2);
d1.appendChild(i3);
var lab33=document.createElement("label");
lab3.innerHTML="Guidlines for DSC user";
lab3.style.paddingLeft="55px";
lab3.style.color="brown";
d1.appendChild(lab3);
document.body.appendChild(d1);

var p5=document.createElement("p");
var l5=document.createElement("label");
l5.innerHTML="Upload Photo";
var i5 =document.createElement("input");
i5.setAttribute("type","text");
i5.style.position="relative";
i5.style.left="155px";
i5.setAttribute("placeholder","choose file");
var l6=document.createElement("label");
l6.innerHTML="No the choosen";
l6.style.paddingLeft="165px";

var l7=document.createElement("label");
l7.innerHTML="Upload Signature";
l7.style.paddingLeft="265px";
var i6 =document.createElement("input");
i6.setAttribute("type","text");
i6.style.position="relative";
i6.style.left="5px";
i6.setAttribute("placeholder","choose file");
var l8=document.createElement("label");
l8.innerHTML="No the choosen";
l8.style.paddingLeft="15px";
p5.appendChild(l5);
p5.appendChild(i5);
p5.appendChild(l6);
p5.appendChild(l7);
p5.appendChild(i6);
p5.appendChild(l8);
document.body.appendChild(p5);

var p6=document.createElement("p");
var l9=document.createElement("label");
l9.innerHTML="Upload Signature";
var i7 =document.createElement("input");
i7.setAttribute("type","text");
i7.style.position="relative";
i7.style.left="125px";
i7.setAttribute("placeholder","choose file");
var l4=document.createElement("label");
l4.innerHTML="No the choosen";
l4.style.paddingLeft="135px";
p6.appendChild(l9);
p6.appendChild(i7);
p6.appendChild(l4);
document.body.appendChild(p6);

var p7=document.createElement("p");
var l9=document.createElement("label");
l9.innerHTML="ALREADY UPLOADED PHOTO:";
var i7 =document.createElement("input");
i7.setAttribute("type","text");
i7.style.position="relative";
i7.style.left="345px";
i7.style.width="45%";
i7.style.height="29px";
p7.appendChild(l9);
p7.appendChild(i7);
document.body.appendChild(p7);

var p7=document.createElement("p");
var l9=document.createElement("label");
l9.innerHTML="ALREADY UPLOADED SIGNATURE:";
var i7 =document.createElement("input");
i7.setAttribute("type","text");
i7.style.position="relative";
i7.style.left="315px";
i7.style.width="45%";
i7.style.height="29px";
p7.appendChild(l9);
p7.appendChild(i7);
document.body.appendChild(p7);

var p7=document.createElement("p");
var l9=document.createElement("label");
l9.innerHTML="ALREADY UPLOADED SIGNATURE:";
l9.style.position="relative";
l9.style.bottom="45px";
var i7 =document.createElement("textarea");
i7.style.position="relative";
i7.style.left="315px";
i7.style.width="45%";
i7.style.height="115px";
p7.appendChild(l9);
p7.appendChild(i7);
document.body.appendChild(p7);

var but=document.createElement("button");
but.innerHTML="submit";
but.style.position="relative";
but.style.left="665px";
document.body.appendChild(but);
